// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG6YXDuVN1CrzDnfQ0jy86AU6rtlXrfDw',
    appId: '1:253838372232:web:2e54937bcf2f225241de3d',
    messagingSenderId: '253838372232',
    projectId: 'btds-mobile',
    authDomain: 'btds-mobile.firebaseapp.com',
    storageBucket: 'btds-mobile.appspot.com',
    measurementId: 'G-QQ28CJ882Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOU-SjmtyqWS21ioXNPzo0nVT5Qu3Scm8',
    appId: '1:253838372232:android:5548e77a6091aedc41de3d',
    messagingSenderId: '253838372232',
    projectId: 'btds-mobile',
    storageBucket: 'btds-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw8bUkohgcjK4YR3KLK6OaXFaHCMv_DNI',
    appId: '1:253838372232:ios:6dcb11f9950712e241de3d',
    messagingSenderId: '253838372232',
    projectId: 'btds-mobile',
    storageBucket: 'btds-mobile.appspot.com',
    iosBundleId: 'com.example.btdsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw8bUkohgcjK4YR3KLK6OaXFaHCMv_DNI',
    appId: '1:253838372232:ios:6dcb11f9950712e241de3d',
    messagingSenderId: '253838372232',
    projectId: 'btds-mobile',
    storageBucket: 'btds-mobile.appspot.com',
    iosBundleId: 'com.example.btdsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG6YXDuVN1CrzDnfQ0jy86AU6rtlXrfDw',
    appId: '1:253838372232:web:d2f808ffabb5ce1e41de3d',
    messagingSenderId: '253838372232',
    projectId: 'btds-mobile',
    authDomain: 'btds-mobile.firebaseapp.com',
    storageBucket: 'btds-mobile.appspot.com',
    measurementId: 'G-G82EW07C6P',
  );
}
